name: Gradle CI

on: [push, pull_request]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 22

      - name: Make gradlew executable
        working-directory: Gradle
        run: chmod +x gradlew

      - name: Run Tests
        working-directory: Gradle
        run: ./gradlew test --tests "sdet.data.OrdersDataIT"